"""empty message

Revision ID: 8e17e704bb42
Revises: 
Create Date: 2022-09-26 16:11:05.725729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e17e704bb42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ram_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('used', sa.String(length=200), nullable=True),
    sa.Column('free', sa.String(length=512), nullable=True),
    sa.Column('total', sa.String(length=512), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ram_usage')
    # ### end Alembic commands ###
